# Build site settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
title: HACKade
description: Hello. This is a project created for our Software Engineering course CS 3354 at UTD during Fall 2022.
show_downloads: true
